import { ColorPalette, EventItem, ScheduleEvent, Coordinator, GalleryItem, NavItem, Sponsor, FestCategory } from './types';

export const COLOR_PALETTES: ColorPalette[] = [
  { name: 'Deep Space', primary: '#ffffff', secondary: '#1e3a8a', accent: '#60a5fa', background: '#030014', text: '#F8FAFC' },
];

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '#home' },
  { label: 'All Events', href: '#all-events' },
  { label: 'Schedule', href: '#schedule' },
  { label: 'Gallery', href: '#gallery' },
  { label: 'Register', href: 'https://forms.gle/ymYNnDf6gBi9C8sK9' },
  { label: 'Contact', href: '#contact' },
];

export const DEPARTMENT_CATEGORIES: Record<string, 'technical' | 'cultural' | 'literary'> = {
  'CSE': 'technical',
  'ECE': 'technical',
  'EE': 'technical',
  'CE': 'technical',
  'ME': 'technical',
  'Bio-Tech': 'technical',
  'B.Pharm': 'cultural',
  'MBA': 'cultural',
  'ASB': 'cultural',
  'CULTURAL': 'cultural',
  'Fine Arts': 'cultural',
  'Literary': 'literary',
};

const img = (q: string) => `https://images.unsplash.com/${q}&auto=format&fit=crop&w=1200&q=70`;

export const EVENTS: EventItem[] = [
  // MBA
  { id: 'mba1', title: 'Innovative Gambit – Pitch the Future', category: 'cultural', department: 'MBA', description: 'Think Bold, Innovate Smart, Lead Ahead. Present your original, innovative, and viable business idea. Faculty: Dr. Sharmila Singh (7619944491), Dr. Rajender Tewari (7754908233). Students: Satya Gupta (8840624370), Anjali Singh.', date: '2026-02-25', time: '10:00 AM onwards', venue: 'F12/F13', image: img('photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3'), prize: 'Certificates & Prizes', rules: ['Individually or in teams of 2–4 members', 'Business idea must be original, innovative, and viable', 'Copied content results in immediate disqualification', 'Prior registration mandatory; report 30 minutes before scheduled time', 'Misconduct or unfair practices lead to disqualification', 'Certificates and prizes awarded to winners and runners-up'], teamSize: '1-4', registrationFee: '₹100' },
  { id: 'mba2', title: 'GD Model Presentation (SEZ in India)', category: 'cultural', department: 'MBA', description: 'Group Discussion on Special Economic Zones in India. Faculty: Dr. Amit Kr. Singh (9415894177), Dr. Vinay Kr. Tiwari (7388069330). Student: Arya Tripathi (9956835027).', date: '2026-02-25', time: '10:00 AM onwards', venue: 'GD Room', image: img('photo-1552664730-d307ca884978?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Refrain from demeaning, discriminatory or harassing behaviour, materials, and speech', 'Professional attire required – no provocative or offensive clothing', 'No intimidating, harassing, abusive, or derogatory conduct', 'No physical, verbal or other abuse, intimidation, threats, or harassment', 'Judges\' decision is final'], teamSize: 'Team', registrationFee: 'TBA' },
  { id: 'mba3', title: 'Fusion Fiesta (Recorded Video)', category: 'cultural', department: 'MBA', description: 'Video content creation competition in recorded format. Faculty: Dr. Charu Agrawal (9997741331), Er. Aditya Singh Yadav (9936062050). Student: Divyanshu Kushwaha (6392209998).', date: '2026-02-26', time: '10:00 AM', venue: 'F-12', image: img('photo-1533158326339-7f3cf2404354?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or teams of 2–5 members', 'Videos should be 60–120 seconds long in MP4 format', 'Minimum 720p resolution with clear audio', 'Content may be in English, Hindi, or bilingual', 'Must not include abusive, political, or religious material', 'Judged on: creativity, clarity, storytelling, technical quality, overall impact', 'Late, plagiarized, or inappropriate submissions will be disqualified', 'Judges\' decision is final'], teamSize: '1-5', registrationFee: '₹100' },
  { id: 'mba4', title: 'MODEX / Poster Gallery', category: 'cultural', department: 'MBA', description: 'Business model presentation based on current business trends. Faculty: Dr. Priti Rai (8840529042), Mr. Rohit Singh (9839255518). Students: Mohd. Asad Ali Khan (9305400154), Shreya Singh.', date: '2026-02-25', time: '10:00 AM', venue: 'F12/F13', image: img('photo-1513364776144-60967b0f800f?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Business model based on current business trends followed by entrepreneurs', 'Should have significance in relation to Management concepts, thoughts, quotes by famous management Gurus', 'Can relate to business tycoons and innovative/successful entrepreneurs', 'Role model industrialists welcome', 'Judges\' decision is final'], teamSize: 'Team', registrationFee: 'TBA' },
  { id: 'mba5', title: 'Management Edu-Talk (Vikshit Bharat 2047)', category: 'cultural', department: 'MBA', description: 'Talk on Sustainable Development and India\'s Vision 2047. Faculty: Dr. Pallavi Singh (8881279991), Mr. Rohit Singh (9839255118). Students: Mukta Mandal (8810829076), Awadhesh Kumar (9540234639).', date: '2026-02-25', time: '11:00 AM onwards', venue: 'Buddha Hall (Ground Floor)', image: img('photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3'), prize: 'Knowledge', rules: ['Stick to the above-mentioned topic', 'Establishing ground rules or guidelines for discussion', 'Avoid blame, speculation, and inflammatory language', 'Use 3-2-1 rule of Speaking', 'Bilingual language allowed strictly (English & Hindi)'], teamSize: 'Audience', registrationFee: 'Free' },
  { id: 'mba6', title: 'Mission Samarthya (Ashoka\'s Social Cause)', category: 'cultural', department: 'MBA', description: 'Humari Soch – Managing a Better Tomorrow. Social initiative focusing on affordable digital education, youth innovation, sustainable growth, and nation-building. Faculty: Prof. Charu Agarwal (9997741331). Students: Divyanshu Kushwaha (6392209998), Tanisha Rai (9532012566).', date: '2026-02-25', time: '10:30 AM', venue: 'F-13', image: img('photo-1559027615-cd4628902d4a?ixlib=rb-4.0.3'), prize: 'Recognition', rules: ['Focuses on affordable digital education, youth innovation, sustainable and ethical growth', 'Management Department supports through Finance, Marketing, HR, and Entrepreneurship', 'Finance manages funding/budgeting, Marketing promotes social awareness', 'HR develops volunteers/leadership, Entrepreneurship creates sustainable business models', 'Students work together to create positive social impact', 'Event held on 25th & 26th Feb 2026'], teamSize: 'Team', registrationFee: '₹100' },
  
  // B.Pharm
  { id: 'pharm1', title: 'AD MAD Show', category: 'cultural', department: 'B.Pharm', description: 'Creative pharmaceutical advertisement performance. Faculty: Dr. Ravi Tripathi, Mr. Somendra Maurya.', date: '2026-02-25', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Each team must have 3–6 participants', 'Time limit: 2–3 minutes per performance', 'Content must be original; copied ads, vulgar, offensive, or inappropriate content is strictly prohibited', 'Use of safe props only; dangerous items are not permitted', 'Pre-recorded audio/video is not allowed', 'Judges\' decision is final'], teamSize: '3-6', registrationFee: 'TBA' },
  { id: 'pharm2', title: 'Pharmacy Quiz', category: 'cultural', department: 'B.Pharm', description: 'Multi-round quiz on pharmacy subjects. Faculty: Mr. Awanish km. Shrivastava, Mr. Vishal Shrivastava.', date: '2026-02-25', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1434030216411-0b793f4b4173?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Each team shall consist of 2–3 participants', 'Quiz includes multiple rounds based on pharmacy subjects', 'Use of mobile phones or electronic gadgets is strictly prohibited', 'Decision of the quiz master/judges is final'], teamSize: '2-3', registrationFee: 'TBA' },
  { id: 'pharm3', title: 'Poster Presentation', category: 'cultural', department: 'B.Pharm', description: 'Scientific poster presentation on pharmaceutical topics. Faculty: Mr. Deepak Prasad, Mr. Anubhav Gupta.', date: '2026-02-25', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1581092918056-0c4c3acd3789?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or team participation (maximum 2 members)', 'Poster size and format should follow organizers\' guidelines', 'Content must be original and free from plagiarism', 'Use of offensive or inappropriate content is not allowed', 'Judges\' decision is final'], teamSize: '1-2', registrationFee: 'TBA' },
  { id: 'pharm4', title: 'Formulation Development', category: 'cultural', department: 'B.Pharm', description: 'Prepare pharmaceutical formulations based on given theme. Faculty: Mr. Rakesh Yadav, Mr. Pankaj Maurya.', date: '2026-02-25', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1532187863486-abf9dbad1b69?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or in teams (maximum 2–3 members)', 'Formulation must be based on the given theme or problem statement', 'Participants must follow standard pharmaceutical procedures and safety norms', 'Only permitted ingredients and materials should be used', 'Formulation must be completed within the allotted time', 'Judges\' decision is final'], teamSize: '1-3', registrationFee: 'TBA' },
  { id: 'pharm5', title: 'Herbal Shots (Flavonoid & Carotenoids)', category: 'cultural', department: 'B.Pharm', description: 'Prepare herbal shots rich in flavonoids and/or carotenoids. Faculty: Mrs. Maulshree Bhandari, Mr. Sunil Kushwaha.', date: '2026-02-25', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1505576399279-565b52d4ac71?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or in teams (maximum 2 members)', 'Must prepare herbal shots rich in flavonoids and/or carotenoids', 'Only natural, herbal ingredients permitted; synthetic additives not allowed', 'Formulation must be safe for consumption and prepared under hygienic conditions', 'Judging: originality, nutritional value, taste, and presentation', 'Judges\' decision is final and binding'], teamSize: '1-2', registrationFee: 'TBA' },
  { id: 'pharm6', title: 'First Aid Competition', category: 'cultural', department: 'B.Pharm', description: 'Demonstrate first aid and emergency response skills. Faculty: Mrs. Sonam Patel, Ms. Manisha Dubey.', date: '2026-02-26', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1584982751601-97dcc096659c?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Each team may consist of 2–3 members', 'Use of mobile phones or electronic gadgets is strictly prohibited', 'Participants must use only the first aid materials provided at the venue', 'Judges\' decision is final and binding'], teamSize: '2-3', registrationFee: 'TBA' },
  { id: 'pharm7', title: 'Pharma Expo', category: 'cultural', department: 'B.Pharm', description: 'Exhibition of pharmaceutical innovations, models, and posters. Faculty: Mr. Sant Laal, Om Prakash Sahani.', date: '2026-02-26', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1581574919402-5b7d733224d6?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or in teams (up to 3 members)', 'Participants must bring and manage their own models/posters/materials', 'Use of hazardous or unsafe materials is strictly prohibited', 'Judges\' decision is final'], teamSize: '1-3', registrationFee: 'TBA' },
  { id: 'pharm8', title: 'Pharmacy Rangoli', category: 'cultural', department: 'B.Pharm', description: 'Rangoli art with pharmacy/healthcare theme. Faculty: Mrs. Sushma Chauhan, Mrs. Preet Kaur.', date: '2026-02-26', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1509281373149-e957c6296406?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Theme must be pharmacy/healthcare related', 'Individual or in teams (maximum 2–3 members)', 'Only dry and eco-friendly materials are allowed', 'Use of ready-made stencils or printed designs is not permitted', 'Judges\' decision is final and binding'], teamSize: '1-3', registrationFee: 'TBA' },
  { id: 'pharm9', title: 'Best Out of Waste', category: 'cultural', department: 'B.Pharm', description: 'Create useful products from waste or recyclable materials. Faculty: Ms. Aditi Singh.', date: '2026-02-26', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1532996122724-e3c354a0b15b?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual or in teams (up to 3 members)', 'Product must be created using waste or recyclable materials only', 'Item must be prepared within the allotted time', 'Judges\' decision is final'], teamSize: '1-3', registrationFee: 'TBA' },
  { id: 'pharm10', title: 'Health Camp', category: 'cultural', department: 'B.Pharm', description: 'Community health check-up camp open to students, staff, and invited participants. Faculty: Dr. Abhishek Gupta (+91-9125671496), Mrs. Surbhi Gupta. Note: ₹200 registration fee for students from other colleges.', date: '2026-02-26', time: '10:00 AM - 2:00 PM', venue: 'Pharma Department', image: img('photo-1576091160550-2173dba999ef?ixlib=rb-4.0.3'), prize: 'Service', rules: ['Open to students, staff, and invited participants', 'All participants must register before availing services', 'Health check-ups provided as per schedule and availability', 'Discipline and hygiene must be maintained at all times', 'Any medical advice or reports are for guidance only', 'Organizers\' decisions are final and binding'], teamSize: 'Open', registrationFee: 'Free (\u20b9200 for other colleges)' },

  // ECE
  { id: 'ece1', title: 'Robo Race (Robo Vega)', category: 'technical', department: 'ECE', description: 'Race robots on an obstacle course track (approx. 80–100 ft) in a 32ft × 24ft arena from Start to Finish Line. Faculty: Mr. Pankaj Vishwakarma. Coordinators: Shivam Kumar, Nageshwar Pandey, Ashish Srivastava, Shubham Kumar (ECE).', date: '2026-02-25', time: '10:00 AM - 1:00 PM', venue: 'Central Ground', image: img('photo-1518779578993-ec3579fee39f?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 3 members', 'Arena: approx. 32ft × 24ft rectangular', 'Track Length: 80–100 ft along the racing path', 'Track Width: 40cm at Start Zone, 80–180cm at wide sections', 'Straight paths, curves, checkpoints, and obstacles included', 'Judges\' decision is final'], teamSize: '3', registrationFee: 'TBA' },
  { id: 'ece2', title: 'Battle of Components & Sensors (Circuit Samar)', category: 'technical', department: 'ECE', description: 'Test your knowledge of electronic components through identification, rapid quiz, and design/debugging rounds. Faculty: Mrs. Anuja Singh & Mr. Pawan Kr. Sinha. Coordinators: Ashwani Maurya, Praveen Kumar, Vineet Kumar Yadav, Ashutosh Dwivedi.', date: '2026-02-25', time: '1:00 PM - 4:00 PM', venue: 'S2 & Embedded System Lab', image: img('photo-1581092160562-40aa08e78837?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Round 1: Identification of Components', 'Round 2: Rapid Quiz', 'Round 3: Design & Debugging', 'Report 15 minutes before round begins', 'Identification must be done without internet assistance', 'Rapid Quiz answers must be submitted within time limit', 'For Design & Debugging, pen/paper or whiteboard may be used', 'Decisions by judges are final'], teamSize: 'Team', registrationFee: '₹100' },
  { id: 'ece3', title: 'ElectRONICA (Yantra Pragya Expo)', category: 'technical', department: 'ECE', description: 'Electronics project exhibition showcasing innovative ideas, technical skills, and practical knowledge in electronics & communication engineering. Faculty: Mr. Pratap Gaurav Upadhyay. Coordinators: Anshu Yadav, Mahima Singh, Rolee Vishwakarma, Vandini Gupta.', date: '2026-02-25', time: '10:00 AM - 4:00 PM', venue: 'ECE Department', image: img('photo-1581092921461-eab62e97a780?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Up to 4 members per team', 'Working model/project mandatory', 'Showcases innovation and practical application', 'Explanation and demonstration required', 'Creativity and problem-solving valued', 'Judges\' decision is final'], teamSize: 'Up to 4', registrationFee: 'TBA' },
  { id: 'ece4', title: 'Guess the Gadget (Yantra Anumana)', category: 'technical', department: 'ECE', description: 'Touch & Feel + Hint based gadget identification game. Faculty: Mr. Lalit Kumar. Coordinators: Supriya Yadav, Tannu Sharma, Vishal Chauhan, Tanya Sharma. Helpline: Ashwini Maurya (6306641530), Shivam (6392451682).', date: '2026-02-26', time: '10:00 AM - 1:00 PM', venue: 'ECE Department', image: img('photo-1550009158-9ebf69173e03?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Up to 2 members per team', 'Participants may not observe the gadget before touch', 'Only one player touches at a time', 'No shaking, sound guessing, or visual attempts', 'Decisions by the host/judges are final'], teamSize: '1-2', registrationFee: '₹100' },

  // EE
  { id: 'ee1', title: 'Maze Navigation Challenge', category: 'technical', department: 'EE', description: 'Navigate racing cars/robotic vehicles through a maze within the given time limit. Vehicles are provided by organizers. Faculty: Mr. Manu Kr. Singh. Coordinator: Vijay Singh Yadav (EE 3rd Year).', date: '2026-02-25', time: '10:00 AM - 4:00 PM', venue: 'Power Electronics Lab', image: img('photo-1597733153203-a54d0fbc47de?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 2 members', 'Racing cars/robotic vehicles will be provided by organizers', 'Participants are NOT permitted to bring their own hardware', 'Must complete the maze within the given time limit', 'External assistance or unfair practice leads to immediate disqualification', 'Judges\' decisions are final and binding', 'Event held on 25th & 26th Feb 2026'], teamSize: '2', registrationFee: '₹200' },
  { id: 'ee2', title: 'Watt\'s The Answer?', category: 'technical', department: 'EE', description: 'Electrical engineering quiz competition with multiple rounds. Faculty: Mr. Sajjad Ali. Coordinator: Suhani Baranwal (EE 2nd Year).', date: '2026-02-26', time: '11:00 AM - 1:00 PM', venue: 'Class Room F-3', image: img('photo-1509228627152-72ae9ae6848d?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual event', 'Quiz may consist of multiple rounds', 'Questions may be objective or subjective', 'Use of electronic devices is strictly prohibited', 'Tie-breaker rounds may be conducted if required', 'The quizmaster\'s decision is final'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'ee3', title: 'Steady Hand Game', category: 'technical', department: 'EE', description: 'Test your steady hand navigating an electrical circuit path. Time and accuracy both evaluated. Faculty: Mr. Avinash Prasad. Coordinator: Sindhu Raj (EE 3rd Year).', date: '2026-02-25', time: '9:30 AM - 4:00 PM', venue: 'Class Room F-1', image: img('photo-1581092334651-ddf26d9a09d0?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual event', 'Touching the sides of the circuit path results in penalty points', 'Time and accuracy will both be considered for evaluation', 'Intentional damage to the setup results in immediate disqualification', 'Judges\' decisions are final', 'Event held on 25th & 26th Feb 2026'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'ee4', title: 'Antardrishti Chitra (Blind Circuit Art)', category: 'technical', department: 'EE', description: 'One team member gives verbal instructions while the other draws a circuit blindly. Judged on accuracy, clarity, and completeness. Faculty: Mr. Sandeep Singh. Coordinator: Sachi Kumari (EE 3rd Year).', date: '2026-02-25', time: '2:00 PM - 4:00 PM', venue: 'Class Room F-1', image: img('photo-1581092583537-20d51b4b4f1b?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 2 members', 'Only verbal instructions are allowed', 'No predefined symbols or templates may be used', 'Drawings judged on accuracy, clarity, and completeness', 'Any form of signalling other than speech is prohibited', 'Judges\' evaluation is final'], teamSize: '2', registrationFee: '₹100' },
  { id: 'ee5', title: 'Yantra Memory Grid', category: 'technical', department: 'EE', description: 'Memory challenge with electrical component symbols. Match symbols accurately to score points. Faculty: Mr. Surendra Khushwaha. Coordinator: Shreya Singh (EE 3rd Year).', date: '2026-02-25', time: '11:00 AM - 12:30 PM', venue: 'Class Room F-1', image: img('photo-1581092580497-e0d23cbdf1b9?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual event', 'Symbols must be matched accurately to score points', 'Incorrect matches may result in negative marking', 'No physical marking or external notes are allowed', 'The participant with the highest score wins', 'Judges\' decisions are final'], teamSize: 'Solo', registrationFee: 'Free' },
  { id: 'ee6', title: 'Volt Vision – Project Expo', category: 'technical', department: 'EE', description: 'Project presentation event featuring innovative electrical engineering projects from first year to final year. Faculty: Mr. S N Singh. Coordinators: Rohit Gautam (EE 3rd Year). Helpline: Priyanshu Upadhyay (9935013600), Vijay Singh Yadav (8423380678).', date: '2026-02-25', time: '9:00 AM - 4:00 PM', venue: 'F-3', image: img('photo-1581092580497-e0d23cbdf777?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of up to 4 members', 'Present innovative electrical engineering projects', 'Platform to showcase technical skills, creativity, and practical solutions', 'Projects from 1st year to final year welcome', 'Event held on 25th & 26th Feb 2026', 'Judges\' decisions are final'], teamSize: 'Up to 4', registrationFee: 'TBA' },

  // CSE
  { id: 'cse1', title: 'Robo Soccer', category: 'technical', department: 'CSE', description: 'Design and fabricate a manually controlled robot to play soccer. Robot must push/guide the ball using movement and strategy only – no grabbing, holding, or lifting allowed. Coordinator: Shreyansh Verma (9554353671).', date: '2026-02-25', time: '10:00 AM onwards', venue: 'D Block', image: img('photo-1501594907352-04cda38ebc29?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 3 members', 'Robot Size ≤ 30×30×20 cm (including wheels)', 'Weight ≤ 5 kg (±2.5%)', 'Wired (≥4m wire) or Wireless (Bluetooth/Wi-Fi/dual frequency)', 'Onboard power mandatory, Electrical power only', 'Allowed batteries: Gel, Lithium, NiCad, Dry cell', 'Voltage ≤ 25.2V DC', 'No grabbing, holding, or lifting the ball', 'Organizer decisions are final'], teamSize: '3', registrationFee: '₹500' },
  { id: 'cse2', title: 'Nitro Race', category: 'technical', department: 'CSE', description: 'High-speed RC vehicle racing competition on Central Ground. Coordinator: Dheeraj Patel (7007551376).', date: '2026-02-25', time: '12:30 PM – 2:30 PM', venue: 'Central Ground', image: img('photo-1525609004556-c46c7d6cf023?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 3 members', 'Robot Size ≤ 25×25×20 cm (±5%)', 'Weight ≤ 3 kg (±2%)', 'Only 1 operator allowed', 'Wired (≥2m wire) or Wireless (Bluetooth/Wi-Fi/Dual frequency)', 'Onboard power required for wireless', 'No LEGO parts or grasping mechanisms', 'Allowed batteries: Gel, Lithium, NiCad, Dry cell, Voltage ≤ 16.8V DC', 'Misconduct leads to disqualification', 'No second attempt for poor performance'], teamSize: '3', registrationFee: '₹500' },
  { id: 'cse3', title: 'Robo Tug of War', category: 'technical', department: 'CSE', description: 'Build a manually controlled robot to pull the opponent robot across a central line. Tests robot power, traction, and structural strength under tension. Coordinator: Satyaprakash (8423360360).', date: '2026-02-25', time: '2:00 PM onwards', venue: 'D Block', image: img('photo-1563968743333-044cef800494?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 3 members', 'No prefabricated LEGO parts, no grasping mechanisms', 'Pré-assembled gear assemblies allowed', 'Electrical power only, Voltage ≤ 16.8V', 'Only 1 operator (no controller change)', 'Wires must remain slack (no pulling to assist)', 'Early start: 1 restart, second = disqualification', 'Maximum 3 manual resets (time penalty)', 'Arena damage = disqualification', 'Misconduct = disqualification'], teamSize: '3', registrationFee: '₹500' },
  { id: 'cse4', title: 'NEXUS 2026 – The Tech Quiz', category: 'technical', department: 'CSE', description: 'Multi-stage technology and computing quiz competition. Coordinator: Veer Gupta (7007828218).', date: '2026-02-26', time: '9:30 AM – 11:30 AM', venue: 'Lab 1', image: img('photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 2 members', 'Stage I (Prelims): 20 Questions (Mixed), No Negative Marking – Top 8–10 qualify', 'Stage II (Logic Gates): 20 MCQs, +10/–5 marking – Top 5 qualify', 'Stage III (Grand Finale): Pounce & Bounce format: +10 (Direct/Pounce), +5 (Pass), –5 (Wrong Pounce)', 'No electronic devices allowed', 'Judges\' decision is final'], teamSize: '2', registrationFee: '₹100' },
  { id: 'cse5', title: 'Code Master', category: 'technical', department: 'CSE', description: 'Competitive coding championship with questions from C and Java. Coordinator: Arpit (9532545307).', date: '2026-02-26', time: '1:00 PM – 3:30 PM', venue: 'Lab 1', image: img('photo-1515879218367-8466d910aaa4?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 3 members', 'Questions from both C and Java programming languages', 'Two categories: Moderate Level and High Level', 'Additional 10 marks for participant behaviour', 'No plagiarism or unfair means', 'Judges\' decision is final'], teamSize: '3', registrationFee: '₹100' },
  { id: 'cse6', title: 'Vibe Coding Competition', category: 'technical', department: 'CSE', description: 'A fast-paced, creativity-driven programming event. Round 1: Coding & Progress Review, Round 2: Presentation. Problem statement and theme revealed on spot. Coordinator: Bal Mukund Kumar (9693233843).', date: '2026-02-25', time: '10:00 AM – 2:00 PM', venue: 'Lab 1', image: img('photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 2 members', 'Round 1: Coding & Progress Review', 'Round 2: Presentation', 'Problem statement and theme revealed on spot at beginning of Round 1', 'All teams must build solution based on provided theme during competition time', 'No pre-written code allowed', 'Organizer decisions are final'], teamSize: '2', registrationFee: '₹200' },
  { id: 'cse7', title: 'BGMI Tournament', category: 'technical', department: 'CSE', description: 'Battlegrounds Mobile India gaming tournament. Coordinators: Suprit Yadav (7905759801), Anshuman Sharma (9569326140).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'G7 & G8', image: img('photo-1552820728-8b83bb6b773f?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Squad of 4 players', 'Players must use their own accounts; account sharing is prohibited', 'Cheating, hacking, or use of unauthorized third-party software results in immediate disqualification', 'Players must join the custom room within given time; late entries not entertained', 'Organizers reserve the right to modify rules if necessary', 'Decisions made by referees/judges are final', 'Disputes must be raised immediately after the match'], teamSize: '4', registrationFee: '₹100' },
  { id: 'cse8', title: 'The Horcrux Hunt (Treasure Hunt)', category: 'technical', department: 'CSE', description: 'Campus-wide treasure hunt with clues, puzzles, and riddles. Coordinator: Manas Agrawal (8318690337).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'College Campus', image: img('photo-1604881991720-f91add269bed?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Each team must consist of maximum 4 members', 'Participants must strictly follow instructions given by event coordinators', 'Any team found cheating or misbehaving will be immediately disqualified', 'Decision of the judges and organizers is final and binding'], teamSize: '4', registrationFee: '₹150' },
  { id: 'cse9', title: 'Velocity Vertices (Rubik\'s Cube)', category: 'technical', department: 'CSE', description: 'Rubik\'s Cube speed-solving competition using Average of 5 (Ao5) format. Coordinator: Amardeep Kumar (7905032220).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'G2', image: img('photo-1635070041078-e363dbe005cb?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of up to 4 members', 'Competition follows the Average of 5 (Ao5) format – five solves per participant', '15 seconds of inspection before each solve; warnings at 8 and 12 seconds', 'After stopping the timer, do not touch the cube until judge verifies', 'Only standard 3×3 or 4×4 cube in clean, proper working condition is permitted', 'Judge\'s decision is final'], teamSize: 'Up to 4', registrationFee: '₹100' },
  { id: 'cse10', title: 'The Escape Room', category: 'technical', department: 'CSE', description: 'Locked inside a themed room filled with hidden clues, puzzles, and riddles. Work as a team to solve all puzzles and escape within the time limit. Coordinator: Smriti Verma (9236189910).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'G2', image: img('photo-1511578314322-379afb476865?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 4 members', 'Locked inside a themed room with hidden clues, puzzles, and riddles', 'Work as a team to solve all puzzles and escape within the time limit', 'Every clue matters – every second counts', 'No external help allowed', 'Judges\' decision is final'], teamSize: '4', registrationFee: '₹150' },
  { id: 'cse11', title: 'Debate Charades', category: 'technical', department: 'CSE', description: 'A unique debate event featuring a Two-Bowl System – one bowl for topic selection, one for randomly assigning FOR/AGAINST positions. Think on your feet! Coordinator: Nikunj Srivastava (9621084001).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'G3', image: img('photo-1591115765373-5207764f72e7?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team event', 'Two-Bowl System: One bowl for selecting the topic, one for randomly assigning FOR/AGAINST positions', 'Teams must think on their feet and defend viewpoints assigned at random', 'Respectful argumentation required', 'Judges\' decision is final'], teamSize: 'Team', registrationFee: '₹150' },
  { id: 'cse12', title: 'Intellect Fusion', category: 'technical', department: 'CSE', description: 'A multi-stage challenge: Emoji Coding → Taskmaster Lite → Control the Chaos → The Pressure Box. Coordinator: Nidhi Yadav (7905623658).', date: '2026-02-26', time: '11:30 AM – 1:30 PM', venue: 'G6', image: img('photo-1573164713988-8665fc963095?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team of 4 members', 'Stage 1 – Emoji Coding: Interpret emoji-based CS concepts; only designated player may answer; no electronic devices', 'Stage 2 – Taskmaster Lite: Construct a structure to hold a bottle 30cm above ground for 10 seconds; verbal guidance from teammates allowed', 'Stage 3 – Control the Chaos: Arrange cups into required structure and balance a ball on top; dropping ball = 10-second penalty; incorrect structures must be rebuilt', 'Stage 4 – The Pressure Box: Identify the false clue among six clues; determine final correct answer; 5 minutes time limit', 'Judges\' decision is final'], teamSize: '4', registrationFee: '₹150' },

  // CE
  { id: 'ce1', title: 'Ice Cream Stick Load Bearing', category: 'technical', department: 'CE', description: 'Build the strongest structure using ice cream sticks and fevicol. The structure bearing the most load wins. Faculty: Mr. Shubham Kumar Singh. Coordinator: Suyash Srivastava (9532349636).', date: '2026-02-25', time: '10:30 AM onwards', venue: 'Hydraulics Lab', image: img('photo-1541888946425-d81bb19240f5?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Teams of 2-4 members', 'Only ice-cream sticks + fevicol allowed', 'Base size: max 20cm × 20cm', 'Height: min 25cm, max 40cm', 'Top flat area: 5cm × 5cm compulsory', 'Time limit: 35 minutes', 'More load bearing = winner', 'Judge\'s decision is final'], teamSize: '2-4', registrationFee: '₹100' },
  { id: 'ce2', title: 'General Engineering Quiz', category: 'technical', department: 'CE', description: 'A multi-round quiz open to all engineering branches testing general and technical knowledge. Faculty: Mr. Anuj Kumar. Coordinator: Sunil Kumar Patel (9454190518).', date: '2026-02-26', time: '10:30 AM onwards', venue: 'F-7', image: img('photo-1434030216411-0b793f4b4173?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Teams of 2 members', 'Open to all engineering branches', 'Multiple rounds: Preliminary, Technical, Rapid Fire', 'Use of mobile phones, smart watches, books, or any unfair means is strictly prohibited', 'Decision of the quiz master/judging panel shall be final and binding'], teamSize: '2', registrationFee: 'Free' },
  { id: 'ce3', title: 'AutoCAD Drawing Competition', category: 'technical', department: 'CE', description: 'CAD design and drafting speed competition using AutoCAD software. Faculty: Mr. Aman Jaiswal. Coordinator: Akhilesh Kumar (8114196973).', date: '2026-02-26', time: '10:30 AM onwards', venue: 'CAD LAB', image: img('photo-1581094271901-8022df4466f9?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual event', 'Drawing problem provided on the spot', 'Time duration: 2 hours', 'Drawing must be prepared only using AutoCAD software', 'Use of internet, blocks, pre-saved files, or templates is strictly prohibited', 'Submission format: .dwg file only, within allotted time', 'Judge\'s decision is final'], teamSize: 'Solo', registrationFee: 'Free' },
  { id: 'ce4', title: 'Paper Tower Challenge', category: 'technical', department: 'CE', description: 'Build the tallest free-standing paper tower that can support weight for at least 30 seconds. Faculty: Dr. Ashwani Kumar Sonkar. Coordinator: Praveen Kumar (7081424564).', date: '2026-02-25', time: '10:30 AM onwards', venue: 'F-5', image: img('photo-1486312338219-ce68d2c6f44d?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Teams of 2-3 members', 'Must construct a free-standing paper tower using materials provided', 'Time limit: 45 minutes', 'Use of glue, tape, thread, cardboard, or any additional materials is strictly prohibited', 'Tower must safely support weight and remain stable for at least 30 seconds', 'If more than one tower supports the weight, the tallest stable tower wins', 'Judges\' decision is final'], teamSize: '2-3', registrationFee: '₹100' },

  // ME
  { id: 'me1', title: 'Junk Yard', category: 'technical', department: 'ME', description: 'Create a creative design or working model from raw materials provided: wood, fevicol, rubber band, iron nails, plywood, etc. Contact: Mr. Amit Kumar Jaiswal (7275006697).', date: '2026-02-25', time: '2:00 PM - 4:00 PM', venue: 'Workshop', image: img('photo-1581092921461-eab62e97a780?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual or team-based event', 'Make creative design or working model with given raw materials', 'Coordinators will provide raw materials and tools', 'Materials: wood, fevicol, rubber band, iron nails, plywood, etc.', 'Judges\' decision is final'], teamSize: '1+', registrationFee: '₹50' },
  { id: 'me2', title: 'Model Exhibition', category: 'technical', department: 'ME', description: 'Present a working model and explain its applications. Selection based on quality of explanation. Contact: Mr. Vibhas Patel (7505441958).', date: '2026-02-26', time: '9:30 AM - 11:00 AM', venue: 'Lawn', image: img('photo-1581092160562-40aa08e78837?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual or team-based event', 'Must present a working model', 'Selection based on explanation of model with applications', 'Judges\' decision is final'], teamSize: '1+', registrationFee: '₹50' },
  { id: 'me3', title: 'Picture Perception Test', category: 'technical', department: 'ME', description: 'Image shown for 3 minutes, then 20 minutes for story writing. Present your story individually in front of the jury. Contact: Mr. Abhay Kumar (9580905242).', date: '2026-02-26', time: '1:00 PM - 3:00 PM', venue: 'Seminar Hall 1', image: img('photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual event', 'Image shown on screen for 3 minutes', '20 minutes for story writing after viewing', 'Project yourself onto the central character', 'Include title, number of persons, age and sex in a rectangular box at top', 'Story should be 100–200 words long', 'Present story in front of jury within 6 minutes', 'Medium of story writing: English only'], teamSize: 'Solo', registrationFee: '₹50' },
  { id: 'me4', title: 'Graphica', category: 'technical', department: 'ME', description: 'Engineering graphics competition where task sheets are provided and participants draw on the system. Contact: Mr. Vibhash Km. Patel (7505441958), Mr. Manish Kumar Singh (9795867324).', date: '2026-02-25', time: '9:30 AM - 11:00 AM', venue: 'CAD/CAM Lab', image: img('photo-1573164713988-8665fc963095?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual event', 'Task sheets provided to each participant', 'Must draw the same on the system separately', 'Best three win based on performance', 'Judges\' decision is final'], teamSize: 'Solo', registrationFee: '₹50' },
  { id: 'me5', title: 'Just Imagine', category: 'technical', department: 'ME', description: 'A creative drawing competition – bring your own stationery items, drawing sheets provided. Contact: Mr. Santosh Kumar (7905175731).', date: '2026-02-26', time: '1:00 PM - 3:00 PM', venue: 'Drawing Hall', image: img('photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual event', 'Participants must bring their own stationery items (drawing tools)', 'Coordinator will provide drawing sheets', 'Best three win based on performance', 'Judges\' decision is final'], teamSize: 'Solo', registrationFee: '₹50' },
  { id: 'me6', title: 'Robotics Presentation', category: 'technical', department: 'ME', description: 'Present a working robot and explain its applications. Contact: Mr. Vibhas Kr. Patel (7505441958).', date: '2026-02-25', time: '12:30 PM - 2:00 PM', venue: 'Robotics Lab', image: img('photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3'), prize: '1st: ₹150, 2nd: ₹100', rules: ['Individual or team-based event', 'Must present a working robot', 'Selection based on explanation of robot with applications', 'Judges\' decision is final'], teamSize: '1+', registrationFee: '₹50' },

  // Bio-Tech
  { id: 'bt1', title: 'Truth Pulse', category: 'technical', department: 'Bio-Tech', description: 'A statement is provided and participants pick a banner – Myth or Fact. The group with the quickest correct answer wins each round. Faculty: Dr. Farhan Ahmed. Coordinators: Prity Pandey (8887980661), Yashashvi Pandey (7905829496).', date: '2026-02-25', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1532187863486-abf9dbad1b69?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Groups of 3 participants', 'A statement is provided – pick Myth or Fact', 'Quickest correct answer wins the round and advances', 'No electronic devices (phones etc.) allowed', 'Judges\' decision is final'], teamSize: '3', registrationFee: '₹100/team' },
  { id: 'bt2', title: 'Step Smart Challenge', category: 'technical', department: 'Bio-Tech', description: 'A strategic movement game where players navigate with limited steps. Faculty: Ms. Arpita Singh. Coordinators: Unnati Patel (9455967134), Rukshar (6393359057).', date: '2026-02-25', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1434030216411-0b793f4b4173?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Group of 4 players', 'Only three steps at a time are allowed', 'Cups must not touch or cross each other', 'Judges\' decision is final'], teamSize: '4', registrationFee: '₹100/team' },
  { id: 'bt3', title: 'Float & Focus', category: 'technical', department: 'Bio-Tech', description: 'A single-player balloon balancing game testing focus and control. Faculty: Ms. Shaini Jaiswal. Coordinators: Mansi Srivastava (9506615396), Jahnvi Rai (9369009334).', date: '2026-02-25', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1513364776144-60967b0f800f?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Single player game', 'Balloon should not fall down', 'Cups must not be touched or displaced', 'If balloon falls or cups move, the game ends', 'Maximum time or successful movement decides the winner'], teamSize: 'Solo', registrationFee: '₹100/team' },
  { id: 'bt4', title: 'Mute Message Mayhem', category: 'technical', department: 'Bio-Tech', description: 'A silent communication game where players pass a message through actions only – the last player must guess correctly. Faculty: Ms. Arifa Siddiqui. Coordinators: Ragini Mishra (9555850754), Akshara Pandey (9219425778).', date: '2026-02-26', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1581092921461-eab62e97a780?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['6–7 players per team', 'Players stand in a straight line', 'First player is shown an action/word by the organizer', 'Each player watches only the person in front', 'Only actions allowed – no speaking', 'The last player guesses the message', 'Correct final answer wins the game'], teamSize: '6-7', registrationFee: '₹100/team' },
  { id: 'bt5', title: 'Link It Fast', category: 'technical', department: 'Bio-Tech', description: 'A fast-paced matching game testing speed and accuracy. Faculty: Dr. Sumedha Ojha. Coordinators: Kriti Kumari (8935914447), Kiwi Kumari (9523877375).', date: '2026-02-26', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Only one chance per player', 'No team help allowed', 'Time limit: 30–60 seconds', 'Wrong match ends the turn', 'Player with maximum correct matches wins'], teamSize: 'Solo', registrationFee: '₹100/team' },
  { id: 'bt6', title: 'Crimson Lab', category: 'technical', department: 'Bio-Tech', description: 'A laboratory-based team challenge with timed sessions. Faculty: Mr. Shubham Yadav. Coordinators: Himank Kumar (9336996251), Shreya Gupta (7007799363).', date: '2026-02-26', time: '10:30 AM onwards', venue: 'BT Dept.', image: img('photo-1505576399279-565b52d4ac71?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Duration: 90 minutes per team', '2 batches (9AM–12:30PM & 1PM–4PM)', 'Capacity: 50-60 students total', 'Team size: 3-4 members', 'Judges\' decision is final'], teamSize: '3-4', registrationFee: '₹100/team' },

  // ASB
  { id: 'asb1', title: 'Ashoka Shark Tank', category: 'cultural', department: 'ASB', description: 'Pitch your startup ideas covering problem identification, proposed solution, target market, revenue model, and competitive advantage. Faculty: Dr. Pradeep Kumar Sonkar, Mr. Shashank Pandey. Students: Ms. Anjali Pandey, Ms. Harshita Nishad (9236325702, 7388372004).', date: '2026-02-26', time: '11:00 AM - 12:30 PM', venue: 'G-11', image: img('photo-1573164713714-d95e436ab8d6?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individually or in teams of 2–4 members', 'Time limit: 10–15 minutes per team', '5–7 minutes for pitching idea + 3–5 minutes Q&A with Sharks', 'Pitch should cover: problem identification, proposed solution, target market, revenue model, uniqueness/competitive advantage, estimated cost & funding requirement', 'Presentation must include PPT (compulsory), charts, models, or prototypes (if available)', 'Judges\' decision is final'], teamSize: '1-4', registrationFee: '₹100' },
  { id: 'asb2', title: 'Advert (Advertisement Making)', category: 'cultural', department: 'ASB', description: 'Advertisement making competition with topics given on the spot via chit system. Faculty: Mr. B.N. Singh, Ms. Sushmita Srivastava. Students: Ms. Sanskriti Srivastava, Ms. Vishakha Rao (8005351977).', date: '2026-02-25', time: '11:00 AM - 12:30 PM', venue: 'G-10', image: img('photo-1552581234-26160f608093?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Team event', 'Each team gets 15 minutes for preparation', 'Max time limit for performing the Ad: 5 minutes', 'Judging: content, spontaneity, adherence to topic, coordination, appeal, humour, stage performance', 'Participants may use simple props; arrange props yourselves', 'Advertisement topics selected through chit system and allotted on the spot'], teamSize: 'Team', registrationFee: '₹100' },
  { id: 'asb3', title: 'No Fire, All Flavors (Cooking without Fire)', category: 'cultural', department: 'ASB', description: 'Create innovative dishes without using fire or live coals. Faculty: Dr. Sarika Singh, Dr. Shalini Singh. Students: Ms. Roshani Yadav, Ms. Samiksha, Mr. Manas Singh (7360012851, 8299825921).', date: '2026-02-25', time: '12:00 PM - 1:30 PM', venue: 'ASB Corridor', image: img('photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Teams of 2–3 members', 'Time limit: 30–45 minutes', 'No fire or live coals allowed', 'Dish should be innovative, hygienic, and aesthetically presented', 'All ingredients must be raw – no pre-cooked items are allowed', 'Use of artificial colors, alcohol, or tobacco products is strictly prohibited'], teamSize: '2-3', registrationFee: '₹50' },
  { id: 'asb4', title: 'Creative Reels', category: 'cultural', department: 'ASB', description: 'Short video content creation competition on given themes (Campus Life, Nature, IKS). Faculty: Dr. Kunjan Pandey, Ms. Rachna Singh. Students: Ms. Geya Singh, Yuvraj Soni (7061313726, 6392851798).', date: '2026-02-25', time: 'TBA', venue: 'G-12', image: img('photo-1579762593131-a52d6b44fcb2?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['All entries must be original work; plagiarism or copied content strictly prohibited', 'Reels must follow the given contest theme (e.g., Campus Life, Nature, IKS)', 'Content must be appropriate, decent, and should not harm or deface college property', 'Duration: 30–40 seconds, including titles and credits', 'Judges\' decision is final'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'asb5', title: 'Rangmanch / Automania', category: 'cultural', department: 'ASB', description: 'Drama performance based on Indian Knowledge System (IKS) theme. Faculty: Mr. Sushil Kumar, Dr. Raju Patel. Students: Ms. Layba Khan, Ms. Tanya Rai, Ms. Anjali Pandey (9140607185, 9696385315).', date: '2026-02-26', time: '12:00 PM - 1:00 PM', venue: 'D Block', image: img('photo-1503095396549-807759245b35?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Maximum 5–6 members in a team', 'Theme should be based on Indian Knowledge System (IKS)', 'Any entry not related to the theme may be disqualified', 'Time limit: 10–15 minutes', 'Participants must bring their own props'], teamSize: '5-6', registrationFee: '₹100' },

  // Cultural
  { id: 'cult0', title: 'Hasna Mana Hai (Stand-Up Comedy)', category: 'cultural', department: 'CULTURAL', description: 'A live comedy act where the participant presents jokes, funny stories, or humorous observations to entertain the audience. Coordinator: Rishikesh (9936466631).', date: '2026-02-27', time: 'TBA', venue: 'Buddha Hall (Ground Floor)', image: img('photo-1527224857830-43a7acc85260?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual event', 'Use of abusive, racist, sexist, or vulgar language is strictly prohibited', 'Political or religiously sensitive content is not allowed', 'Time limit for performance: 5 minutes', 'Judging: Originality of content, Delivery & confidence, Audience engagement, Time management'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'cult1', title: 'Melody in Sync (Solo Singing)', category: 'cultural', department: 'CULTURAL', description: 'One participant performs a song individually in front of the audience and judges. Any song of their choice (NO Bhojpuri Songs). Coordinator: Stuti Srivastava (8808096022).', date: '2026-02-27', time: 'TBA', venue: 'New Seminar Hall', image: img('photo-1516280440614-37939bbacd81?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual participation event', 'Time limit for performance: 3 minutes', 'Participants may perform any genre (classical, semi-classical, folk, or contemporary)', 'Karaoke/backing tracks must be submitted to the organizing team prior to the performance', 'Participants have to bring their own instruments', 'Lyrics must be appropriate and non-offensive', 'Judging: Vocal quality, Rhythm & pitch, Stage presence, Song selection'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'cult2', title: 'Twin Tunes (Duet Singing)', category: 'cultural', department: 'CULTURAL', description: 'Two participants perform a song together as a pair. Coordination, harmony, and synchronization between both singers will be the key focus along with voice quality. Coordinator: Shreya Yadav (6386257445).', date: '2026-02-27', time: 'TBA', venue: 'New Seminar Hall', image: img('photo-1511379938547-c1f69419868d?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This event shall consist of two participants per team', 'Time limit for performance: 3–5 minutes', 'Participants may bring their own musical instruments if required', 'Proper coordination between singers is mandatory', 'Backing tracks must be submitted prior to the event', 'Judging: Vocal harmony & coordination, Rhythm & pitch, Stage presence, Song selection'], teamSize: '2', registrationFee: '₹150' },
  { id: 'cult3', title: 'Stagebound (Solo Dance)', category: 'cultural', department: 'CULTURAL', description: 'A solo dance competition where one participant dances individually on stage to a chosen or assigned music track. Coordinator: Astha Keshari (6386170046).', date: '2026-02-27', time: 'TBA', venue: 'New Seminar Hall', image: img('photo-1508700929628-666bc8bd84ea?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual participation event', 'Time limit for each performance: 3 minutes', 'Any dance form is permitted (classical, semi-classical, folk, western, or contemporary)', 'Music tracks must be submitted to the organizing team prior to the performance in the prescribed format', 'Props are allowed but must be informed and approved by the organizers in advance', 'Judging: Choreography & technique, Expressions & stage presence, Rhythm, timing & coordination, Energy & overall impact, Stage utilization'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'cult4', title: 'Dance Dazzle (Duet Dance)', category: 'cultural', department: 'CULTURAL', description: 'Two participants perform a dance together. The focus is on coordination, synchronization, creativity, and stage presence as a pair. Coordinator: Pranjali (8467938945).', date: '2026-02-27', time: 'TBA', venue: 'New Seminar Hall', image: img('photo-1504609813442-a8924e83f76e?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Each team shall consist of two participants', 'Time limit for performance: 3–5 minutes', 'Any dance form is permitted, including fusion styles', 'If fusion is performed, the routine must include both western and classical dance styles', 'Both styles must be integrated seamlessly on the same beat', 'Emphasis on synchronization, coordination, and concept clarity', 'Music tracks must be submitted prior to the event', 'Performances must be appropriate and culturally respectful', 'Judging: Synchronization & coordination, Choreography & technique, Fusion concept / creativity, Expression, energy & overall presentation'], teamSize: '2', registrationFee: '₹150' },
  { id: 'cult5', title: 'Style Spectrum (Fashion Show)', category: 'cultural', department: 'CULTURAL', description: 'A stage-based event where participants present themed outfits through confident walks, expressions, and coordinated movements. Creativity, style, and storytelling through clothing. Coordinators: Manas Agrawal (8318690337), Niyati Singh (9451378186).', date: '2026-02-27', time: 'TBA', venue: 'New Seminar Hall', image: img('photo-1469334031218-e382a71b716b?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is a team event with approximately 16 participants per team', 'Teams may present their own original theme', 'Participants must bring their own costumes, props, and music track', 'Costumes and performances must be decent and appropriate', 'Props must be safe and should not damage the stage or venue', 'Any vulgar or offensive content will lead to disqualification', 'Participants must follow instructions given by the organizers', 'Judging: Theme interpretation & originality, Costume design & creativity, Stage presence & confidence, Coordination & walk sequence, Overall visual impact'], teamSize: '~16', registrationFee: 'TBA' },

  // Fine Arts
  { id: 'art0', title: 'Comicmania (Comic Designing)', category: 'cultural', department: 'Fine Arts', description: 'An individual comic designing event where participants create a theme-based comic strip with multiple panels, combining artwork and dialogues to tell a clear, creative story within the given time. Coordinator: Abhinya Srivastava (6307485911).', date: '2026-02-27', time: '10:00 AM - 2:00 PM', venue: 'Classroom G7', image: img('photo-1611532736597-de2d4265fba3?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual participation event', 'Participants will be provided with A3 size sheets', 'The theme will be announced 30 minutes prior to the event', 'Participants may use pencils, pens, colours, or sketch pens (bring their own)', 'The comic must contain at least 4 panels telling a clear story', 'Dialogues/captions must be included in the comic', 'Use of mobile phones or reference materials is strictly prohibited', 'Content must not be offensive, vulgar, anti-religious, or inappropriate', 'Time limit: 90 minutes', 'Judging: Creativity & originality, Clarity of sequence & storytelling, Artistic quality & presentation, Use of dialogues/captions & expressions, Relevance to the given theme'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'art1', title: 'Moment in Motion (Time-Lapse Video)', category: 'cultural', department: 'Fine Arts', description: 'A time-lapse video competition where participants record a process or scene over a long period of time and then speed it up to create a short, visually engaging video. Coordinator: Archit Singh (8887604928).', date: '2026-02-27', time: '10:00 AM - 2:00 PM', venue: 'Classroom G8', image: img('photo-1492691527719-9d1e07e534b4?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is a duet (two-member team) event', 'Participants must record raw footage for approximately 3 hours based on the given theme', 'The final submission must be a time-lapse video of 15–30 seconds', 'The theme will be announced on the spot and must be strictly followed', 'Participants must use their own recording devices (mobile phones or cameras)', 'Editing must be done within the given time frame using basic editing tools only', 'Previously recorded clips or external footage are strictly prohibited', 'The final video must be submitted in the prescribed format within the allotted time', 'Content must be original, appropriate, and free from offensive or copyrighted material', 'Judging: Relevance to theme, Creativity & concept, Smoothness & visual flow, Technical clarity & framing, Overall impact'], teamSize: '2', registrationFee: '₹150' },
  { id: 'art2', title: 'Henna Hallows (Mandala Art with Henna)', category: 'cultural', department: 'Fine Arts', description: 'An individual mandala art event using henna on provided sheets, judged on symmetry, detailing, neatness, creativity, and effective time management within the given duration. Coordinator: Gauranshi (8957332234).', date: '2026-02-27', time: '10:00 AM - 2:00 PM', venue: 'Classroom G9', image: img('photo-1513364776144-60967b0f800f?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual event', 'Participants will be provided with A4 size sheets', 'Two henna cones will be provided per participant', 'No additional materials are permitted', 'Time limit: 60 minutes', 'Judging: Symmetry & detailing, Neatness & precision, Creativity, Time management'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'art3', title: 'Kala Darpan (Theme-Based Sketching)', category: 'cultural', department: 'Fine Arts', description: 'An individual sketching competition where participants create artwork on a given theme using provided materials, judged on creativity, theme relevance, technical skill, and overall presentation. Coordinator: Arshya Rai (6393138630).', date: '2026-02-27', time: '10:00 AM - 2:00 PM', venue: 'Graphics Lab', image: img('photo-1460661419201-fd4cecdf8a8b?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual event', 'A3 size sheets will be provided', 'The theme will be announced 30 minutes prior to the event', 'Basic pencils will be provided', 'Time limit: 90 minutes', 'Judging: Relevance to theme, Concept & creativity, Technical skills, Presentation'], teamSize: 'Solo', registrationFee: '₹100' },
  { id: 'art4', title: 'Curl & Create (Quilling Art)', category: 'cultural', department: 'Fine Arts', description: 'An individual quilling art competition where participants create original artwork on a given theme using paper filigree techniques, judged on creativity, precision, technique, color composition, and overall visual appeal. Coordinator: Suhani Baranwal (9026428616).', date: '2026-02-27', time: '10:00 AM - 2:00 PM', venue: 'Classroom G7', image: img('photo-1452860606245-08befc0ff44b?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['This is an individual participation event', 'Artwork must be created using quilling (paper filigree) technique only', 'The theme will be announced on the spot', 'Base sheet/cardboard will be provided by the organizers', 'Participants may bring their own quilling paper strips, tools, and glue', 'Use of pre-made or pre-prepared quilling elements is strictly prohibited', 'Time limit: 90 minutes', 'Use of mobile phones, reference materials, or external assistance is not allowed', 'Any violation of rules may lead to disqualification', 'Judging: Creativity & originality, Neatness & precision of quilling work, Complexity & technique, Color combination & composition, Overall visual appeal & finishing'], teamSize: 'Solo', registrationFee: '₹100' },

  // Literary
  { id: 'lit0', title: 'Panel Samvad', category: 'literary', department: 'Literary', description: 'Panel discussion on Academic Upskilling & Faculty Leadership. Faculty: Dr. Priti Rai, Dr. Sarika Singh. Duration: 40–60 minutes.', date: '2026-02-27', time: '10:30 AM', venue: 'Seminar Hall 1', image: img('photo-1560523159-6b681a1e1852?ixlib=rb-4.0.3'), prize: 'Knowledge', rules: ['Panel discussion format with moderator and panelists', 'Theme: Academic Upskilling & Faculty Leadership', 'Duration: 40–60 minutes', 'Interactive audience Q&A session included', 'Professional conduct required throughout', 'Organized by Dr. Priti Rai & Dr. Sarika Singh'], teamSize: 'Audience', registrationFee: 'Free' },
  { id: 'lit1', title: 'Nari Talk – Financial Independence for Women', category: 'literary', department: 'Literary', description: 'Empowering talk on Financial Independence for Women. Faculty: Dr. Shachi Tiwari.', date: '2026-02-27', time: '11:40 AM', venue: 'Seminar Hall 1', image: img('photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3'), prize: 'Knowledge', rules: ['Participants must speak in English or Hindi', 'No political propaganda or hate speech', 'Content must be respectful, factual, and empowering', 'Time limit per speaker: 3–5 minutes', 'No notes or written aids on stage', 'Focus on Financial Independence for Women', 'Faculty Coordinator: Dr. Shachi Tiwari'], teamSize: 'Audience', registrationFee: 'Free' },
  { id: 'lit2', title: 'Declamation – Rise of Virtual Influencers', category: 'literary', department: 'Literary', description: 'Memorized speech competition on the theme: The Rise of Virtual Influencers – Impact on GenZ and GreenTech Revolution. Faculty: Ms. Sushmita Srivastava.', date: '2026-02-27', time: '12:30 PM', venue: 'Seminar Hall', image: img('photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Participants must deliver a memorized speech (no reading)', 'Time limit: 3–5 minutes', 'No notes, mobile phones, or cue cards allowed on stage', 'Speech must be original', 'Theme: The Rise of Virtual Influencers – Impact on GenZ and GreenTech Revolution', 'Judging: content, delivery, body language, confidence, and time adherence', 'Faculty Coordinator: Ms. Sushmita Srivastava'], teamSize: 'Solo', registrationFee: 'Free' },
  { id: 'lit3', title: 'Lafz & Layer – Kavita Sangrah', category: 'literary', department: 'Literary', description: 'Poetry, micro-prose, and spoken word competition. Theme: दिखावा बनाम हकीकत (Appearance vs Reality). Faculty: Mr. Awanish Srivastava. Helpline: Dr. Pallavi Singh (8881279991).', date: '2026-02-27', time: '2:00 PM', venue: 'Seminar Hall 1', image: img('photo-1455390582262-044cdead277a?ixlib=rb-4.0.3'), prize: 'TBA', rules: ['Individual participation only', 'Poetry, micro-prose, or spoken word formats accepted', 'Bilingual (Hindi/English) allowed', 'Time limit: 3 minutes per participant', 'One team per college', 'Theme: दिखावा बनाम हकीकत (Appearance vs Reality)', 'Faculty Coordinator: Mr. Awanish Srivastava', 'Helpline: Dr. Pallavi Singh (8881279991)'], teamSize: 'Solo', registrationFee: 'Free' },
];

export const SCHEDULE: ScheduleEvent[] = [
  // Day 1 (23rd)
  { id: 's1', eventId: 't1', title: 'Cosmic Code Hackathon', category: 'technical', date: '2026-02-23', startTime: '09:00', endTime: '24:00', venue: 'Innovation Lab Complex', day: 1 },
  { id: 's2', eventId: 't2', title: 'RoboRace', category: 'technical', date: '2026-02-23', startTime: '10:00', endTime: '13:00', venue: 'Mechanical Quad', day: 1 },
  { id: 's3', eventId: 't3', title: 'Line Follower', category: 'technical', date: '2026-02-23', startTime: '14:00', endTime: '16:00', venue: 'Mechanical Quad', day: 1 },
  // Day 2 (24th)
  { id: 's4', eventId: 't4', title: 'Algo Arena', category: 'technical', date: '2026-02-24', startTime: '10:00', endTime: '12:30', venue: 'CS Block Lab-3', day: 2 },
  { id: 's5', eventId: 't5', title: 'App Dev Sprint', category: 'technical', date: '2026-02-24', startTime: '13:30', endTime: '17:30', venue: 'Innovation Lab Complex', day: 2 },
  // Day 3 (25th)
  { id: 's6', eventId: 'c3', title: 'Battle of Bands', category: 'cultural', date: '2026-02-25', startTime: '10:00', endTime: '13:00', venue: 'Main Auditorium', day: 3 },
  { id: 's7', eventId: 'c2', title: 'Group Dance - Rhythmic Galaxy', category: 'cultural', date: '2026-02-25', startTime: '14:00', endTime: '17:00', venue: 'Main Auditorium', day: 3 },
  { id: 's8', eventId: 'c4', title: 'Fashion Show - Starlit Runway', category: 'cultural', date: '2026-02-25', startTime: '17:30', endTime: '19:00', venue: 'OAT Runway', day: 3 },
  { id: 's9', eventId: 'c1', title: 'Celestial Beats (Pro-Show)', category: 'cultural', date: '2026-02-25', startTime: '19:00', endTime: '22:00', venue: 'Main Stage (OAT)', day: 3 },
  // Day 4 (26th)
  { id: 's10', eventId: 'l1', title: 'Nebula Narratives', category: 'literary', date: '2026-02-26', startTime: '10:00', endTime: '12:00', venue: 'Seminar Hall A', day: 3 },
  { id: 's11', eventId: 'l2', title: 'Poetry Slam', category: 'literary', date: '2026-02-26', startTime: '12:30', endTime: '14:00', venue: 'Seminar Hall A', day: 3 },
  { id: 's12', eventId: 'l4', title: 'JAM', category: 'literary', date: '2026-02-26', startTime: '11:00', endTime: '13:00', venue: 'Amphitheatre', day: 3 },
  { id: 's13', eventId: 'l3', title: 'Debate - Orion Open', category: 'literary', date: '2026-02-26', startTime: '14:30', endTime: '17:30', venue: 'Seminar Hall B', day: 3 },
  { id: 's14', eventId: 'l5', title: 'Lit Quiz - Quasar Quest', category: 'literary', date: '2026-02-26', startTime: '15:00', endTime: '17:00', venue: 'Seminar Hall B', day: 3 },
];

export const COORDINATORS: Coordinator[] = [
  // Faculty (Technical Wing)
  { id: 'f1', name: 'Mr. Sandeep Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8869961230' },
  { id: 'f2', name: 'Mr. Alok Kr. Gupta', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9838252782' },
  { id: 'f3', name: 'Mr. Akhilesh Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8115537253' },
  { id: 'f4', name: 'Mrs. Kavita Patel', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9911909220' },
  { id: 'f5', name: 'Mrs. Alka Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '7905062119' },
  { id: 'f6', name: 'Ms. Astha Pathak', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9369287994' },
  // Faculty (Non-Technical Wing)
  { id: 'f7', name: 'Mr. Vibhanshu S. Pandey', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9415868055' },
  { id: 'f8', name: 'Mr. Sunil Kumar', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9795496291' },
  { id: 'f9', name: 'Mrs. Saumya Misrha', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8299068601' },
  { id: 'f10', name: 'Mrs. Akanksha Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '6387008534' },
  { id: 'f11', name: 'Mr. Ravindra', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '7080688259' },
  // Faculty (Decoration & Project Showcase Wing)
  { id: 'f12', name: 'Mrs. Reena Mishra', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8005315856' },
  { id: 'f13', name: 'Mr. Pankaj Kumar', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9140877393' },
  { id: 'f14', name: 'Ms. Astha Pathak', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9369287995' },
  { id: 'f15', name: 'Mr. Manikant Sharma', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8005040333' },
  { id: 'f16', name: 'Mr. Akhilesh Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '8115537253' },
  { id: 'f17', name: 'Mrs. Alka Singh', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '7905062119' },
  { id: 'f18', name: 'Mrs. Kavita Patel', role: 'Faculty Coordinator', type: 'faculty', department: 'CSE', phone: '9911909220' },

  // Students (Technical Wing)
  { id: 's1', name: 'Sobrat Dayal', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '9565676988' },
  { id: 's2', name: 'Sonu Dubey', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '9219005627' },
  { id: 's3', name: 'Sujal Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8840878909' },
  { id: 's4', name: 'Arpit Sharma', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '9532545307' },
  { id: 's5', name: 'Dheeraj Patel', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8604539294' },
  { id: 's6', name: 'Uday Singh', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8917793280' },
  { id: 's7', name: 'Aditya Dubey', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '3rd', phone: '8932056388' },
  { id: 's8', name: 'Ansh Jaiswal', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '3rd', phone: '6393170047' },
  { id: 's9', name: 'Samarth Rao', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '3rd', phone: '8960356600' },
  { id: 's10', name: 'Diwakar Patel', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '3rd', phone: '9235508350' },
  { id: 's11', name: 'Simran Singh', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '3rd', phone: '7380352484' },
  { id: 's12', name: 'Balmukund Kumar', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '9693233843' },
  { id: 's13', name: 'Khushi Kushwaha', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '9452734508' },
  { id: 's14', name: 'Disha Jaiswal', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '8707722730' },
  { id: 's15', name: 'Sankalp Jaiswal', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '8081487205' },
  { id: 's16', name: 'Satendar', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '7380346975' },
  { id: 's17', name: 'Veer Gupta', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '7007828218' },
  { id: 's18', name: 'Shivam Patel', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '8957101854' },
  { id: 's19', name: 'Aryan Rai', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '8736820465' },
  { id: 's20', name: 'Vibhas Srivastava', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '9450198419' },
  { id: 's21', name: 'Suprit Yadav', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '7905759801' },
  { id: 's22', name: 'Nivesh Seth', role: 'Student Volunteer', type: 'student', department: 'DS', year: '2nd', phone: '8303531397' },
  { id: 's23', name: 'Adhar Gupta', role: 'Student Volunteer', type: 'student', department: 'BCA', year: '2nd', phone: '9219555632' },
  { id: 's24', name: 'Chanchal Vishvakarma', role: 'Student Volunteer', type: 'student', department: 'BCA', year: '2nd', phone: '8853392683' },
  { id: 's25', name: 'Raunak Yadav', role: 'Student Volunteer', type: 'student', department: 'BCA', year: '2nd', phone: '9369607758' },

  // Students (Non-Technical Wing)
  { id: 's26', name: 'Stuti Srivastava', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8809809602' },
  { id: 's27', name: 'Manas Agrawal', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8318690337' },
  { id: 's28', name: 'Akshat Ramdohkar', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '7668236458' },
  { id: 's29', name: 'Anlit Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8299076240' },
  { id: 's30', name: 'Aryan Kr. Maurya', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '6393517001' },
  { id: 's31', name: 'Pranav Pandey', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '9305352754' },
  { id: 's32', name: 'Avika Srivastava', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '9696210163' },
  { id: 's33', name: 'Nidhi Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '7905623658' },
  { id: 's34', name: 'Anuj Rajpoot', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '8957508689' },
  { id: 's35', name: 'Aayushi Jaiswal', role: 'Student Volunteer', type: 'student', department: 'CSE-A', year: '2nd', phone: '8303524300' },
  { id: 's36', name: 'Veer Gupta', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '7007828218' },
  { id: 's37', name: 'Riya Mishra', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '9555435837' },
  { id: 's38', name: 'Srishti Srivastava', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '9044589065' },
  { id: 's39', name: 'Smriti Verma', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '9236189910' },
  { id: 's40', name: 'Unnati Juneja', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '9580654533' },
  { id: 's41', name: 'Shraddha Dubey', role: 'Student Volunteer', type: 'student', department: 'CSE-B', year: '2nd', phone: '6306385894' },
  { id: 's42', name: 'Nikunj Srivastava', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '9621084001' },
  { id: 's43', name: 'Priyashi Maurya', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '6307961261' },
  { id: 's44', name: 'Tanya Tripathi', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '9305957765' },
  { id: 's45', name: 'Dhwani Gupta', role: 'Student Volunteer', type: 'student', department: 'DS', year: '2nd', phone: '7668529977' },
  { id: 's46', name: 'Anshi Singh', role: 'Student Volunteer', type: 'student', department: 'DS', year: '2nd', phone: '7355491722' },

  // Students (Decoration & Project Showcase Wing)
  { id: 's47', name: 'Diksha Maurya', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8809809602' },
  { id: 's48', name: 'Arun Rai', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8318690337' },
  { id: 's49', name: 'Divya Gupta', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '7668236458' },
  { id: 's50', name: 'Astitva Raghuvanshi', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '8299076240' },
  { id: 's51', name: 'Kanishka Goyal', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '3rd', phone: '6393517001' },
  { id: 's52', name: 'Krishika Jaiswal', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '9305352754' },
  { id: 's53', name: 'Jahnvi Keshri', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '9696210163' },
  { id: 's54', name: 'Chandraprakash Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '7905623658' },
  { id: 's55', name: 'Abhay Pratap Singh', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '8957508689' },
  { id: 's56', name: 'Roshni Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '8303524300' },
  { id: 's57', name: 'Shalu Singh', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '7007828218' },
  { id: 's58', name: 'Rohan Yadav', role: 'Student Volunteer', type: 'student', department: 'CSE', year: '2nd', phone: '9555435837' },
  { id: 's59', name: 'Rhythm Gupta', role: 'Student Volunteer', type: 'student', department: 'AIML', year: '2nd', phone: '9044589065' },
  { id: 's60', name: 'Satyarth Mishra', role: 'Student Volunteer', type: 'student', department: 'DS', year: '2nd', phone: '9236189910' },
  { id: 's61', name: 'Swati Singh', role: 'Student Volunteer', type: 'student', department: 'BCA', year: '2nd', phone: '9580654533' },
  { id: 's62', name: 'Tanishka', role: 'Student Volunteer', type: 'student', department: 'BCA', year: '2nd', phone: '6306385894' },
];

export const GALLERY: GalleryItem[] = [
  { id: 'g1', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/3b3daad0-67ce-4b63-b47a-9cf7b4b6aba7.png', alt: 'Gallery Image 1', category: 'highlights', year: '2026' },
  { id: 'g2', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/7735f666-c401-440c-b49e-6990132240d3.png', alt: 'Gallery Image 2', category: 'highlights', year: '2026' },
  { id: 'g3', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/c5f5a74a-d656-4d7b-8cbc-1ec166e7d33a.png', alt: 'Gallery Image 3', category: 'highlights', year: '2026' },
  { id: 'g4', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/6dbc8a9d-47ca-40ee-a1f6-0c66635c1e2c.png', alt: 'Gallery Image 4', category: 'highlights', year: '2026' },
  { id: 'g5', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/676ab6da-9af7-45bd-b9b9-c7dfd6b97239.png', alt: 'Gallery Image 5', category: 'highlights', year: '2026' },
  { id: 'g6', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/aff0eda8-97d9-4b03-955d-564195059aa3.png', alt: 'Gallery Image 6', category: 'highlights', year: '2026' },
  { id: 'g7', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/09ee8e0b-774d-4ac6-8b38-04c0edb37219.png', alt: 'Gallery Image 7', category: 'highlights', year: '2026' },
  { id: 'g8', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/954a3897-9dde-45a3-ad7d-cafdd7336f08.png', alt: 'Gallery Image 8', category: 'highlights', year: '2026' },
  { id: 'g9', src: 'https://abhyuday25-ashoka-webfest-hub.vercel.app/lovable-uploads/7e7bb29d-5fa6-4a99-ab86-eb9204a0e170.png', alt: 'Gallery Image 9', category: 'highlights', year: '2026' },
];

export const SPONSORS: Sponsor[] = [
  { name: 'TechNova', tier: 'platinum', logo: 'https://dummyimage.com/160x60/ffffff/222222&text=TechNova', website: '#' },
  { name: 'CodeWorks', tier: 'gold', logo: 'https://dummyimage.com/140x50/ffffff/222222&text=CodeWorks', website: '#' },
];
